### ISSUE TITLE
关于datagrid

### ISSUE THREAD

**Issue by zhanxh** [ptddqr/bootstrap-wpf-style#1]
请问楼主，datagrid在双击单元格进入编辑状态后，可编辑单元格的样式设置，比如宽高字体颜色，试了好久没试出来。

**Comment by ptddqr** [comment]
想控制编辑状态的样式 可以用DataGridTemplateColumn 在CellEditingTemplate里放入你想要的控件和样式

也可以在DataGridCell的样式里加触发器 通过属性IsEditing="true"来触发 可以改变属性值或替换Template
